### ISSUE TITLE
selenium4-函数版本变化

### ISSUE THREAD

**Issue by LiuZhipeng99** [stingbo/pystest#14]
根据[官网示例](https://www.selenium.dev/zh-cn/documentation/webdriver/browser_manipulation/#%E5%88%87%E6%8D%A2%E7%AA%97%E5%8F%A3%E6%88%96%E6%A0%87%E7%AD%BE%E9%A1%B5)，改为如下
--- `utils/actions.py`
![image](https://user-images.githubusercontent.com/44400198/143430174-bc9e4019-348a-4b44-b858-b714161e2f00.png)

**Comment by stingbo** [comment]
:+1: 谢谢
